- name: install openjdk and apache-tomcat
  hosts: all
  user: root
  
  tasks:
  
  - name: Install OpenJDK 11
    apt: name=openjdk-11-jre-headless
    
  - name: Download Tomcat
    get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz dest=/opt/apache-tomcat-8.5.72.tar.gz

  - name: Extract archive
    unarchive:
        src: /opt/apache-tomcat-8.5.72.tar.gz
        dest: /
        remote_src: yes

