pipeline {
    agent any
    
    stages {

        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Build') {
            steps {
                sh './gradlew build'
            }
        }
        
        stage('Artifactory') {
            steps{
                rtUpload(
                    serverId: "jfrog-temafinal",
                    spec:
                        """{
                            "files": [
                                {
                                    "pattern": "build/libs/temafinal01.war",
                                    "target": "cloud-native-temafinal01"
                                }
                            ]
                    }"""
                )
            }
        }
    }
}
